import Link from 'next/link';
import { LockKeyhole, Phone } from 'lucide-react';

const sections = [
  ['Information we collect', 'We may collect information you provide through appointments, forms, phone calls, emails, and other communications. This can include contact details, appointment information, insurance-related information, and information needed to provide orthotic and prosthetic care.'],
  ['How we use information', 'Genfinity O&P uses information to schedule and coordinate care, respond to questions, process insurance and billing matters, provide service-related updates, and support the safety and operation of our website and communications.'],
  ['How information may be shared', 'Information may be shared only as needed to provide services, process payments or insurance, meet legal obligations, or work with trusted service providers supporting our operations. We do not sell personal information.'],
  ['Protecting your information', 'We use reasonable administrative, technical, and physical safeguards designed to protect information entrusted to us. No online system can be guaranteed completely secure, so please avoid sending urgent or highly sensitive medical information through ordinary email.'],
  ['Your choices', 'You may contact us to request updates to your contact information, ask questions about this policy, or manage communication preferences.'],
  ['SMS privacy', 'SMS consent is not shared with third parties or affiliates for marketing purposes. Your mobile number and consent information are used only for the service-related purposes described in our communications and Terms & Conditions.'],
];

export default function PrivacyPage() {
  return <div className="bg-white"><section className="relative overflow-hidden bg-brand-ink py-20 text-white sm:py-28"><div className="hero-grid absolute inset-0 opacity-25"/><div className="relative mx-auto max-w-3xl px-4 text-center sm:px-6"><LockKeyhole className="mx-auto h-9 w-9 text-brand-red"/><p className="mt-5 text-sm font-bold uppercase tracking-[.2em] text-brand-red">Privacy &amp; policies</p><h1 className="mt-4 text-4xl font-bold sm:text-6xl">Your information deserves care.</h1><p className="mt-6 text-lg leading-relaxed text-white/70">Effective date: January 1, 2026</p></div></section><main className="mx-auto max-w-4xl px-4 py-16 sm:px-6 sm:py-24"><p className="text-lg leading-relaxed text-slate-600">Genfinity O&amp;P is committed to protecting the privacy, confidentiality, and security of the information entrusted to us. As an orthotic and prosthetic care provider, we recognize the importance of safeguarding personal and health-related information.</p><div className="mt-12 space-y-10">{sections.map(([title,body])=><section key={title} className="border-b border-brand-ink/10 pb-10"><h2 className="text-2xl font-bold text-brand-ink">{title}</h2><p className="mt-4 leading-relaxed text-slate-600">{body}</p></section>)}</div><section className="mt-12 rounded-3xl bg-brand-ink p-8 text-white sm:p-10"><h2 className="text-2xl font-bold">Questions about privacy?</h2><p className="mt-3 text-white/70">Contact Genfinity O&amp;P and our team will help with your question.</p><a href="tel:8885526188" className="mt-6 inline-flex items-center gap-2 font-bold text-brand-red"><Phone className="w-5 h-5"/> (888) 552-6188</a><p className="mt-6 text-sm text-white/60">This policy may be updated from time to time. Updates will be posted on this page.</p></section><p className="mt-8 text-sm text-slate-500">See also: <Link className="font-semibold text-brand-red" href="/terms">Terms &amp; Conditions</Link></p></main></div>;
}
