import Link from "next/link";
import { LockKeyhole, Phone } from "lucide-react";

const sections = [
  ["Information we collect", "We may collect information you provide through appointments, patient and contact forms, phone calls, emails, SMS conversations, and other communications. This can include your name, address, email address, mobile and other phone numbers, appointment information, insurance and billing information, and information needed to provide orthotic and prosthetic care. We may also collect consent records such as the date, time, method, purpose, and phone number associated with an SMS opt-in or opt-out."],
  ["How we use information", "Genfinity O&P uses information to respond to requests, schedule and coordinate care, provide clinical services, verify benefits, process insurance and billing matters, send requested appointment reminders and service notifications, answer customer-care questions, maintain records, improve the safety and operation of our website, and comply with legal obligations. We do not use SMS consent to send unrelated marketing messages without the consent required by law."],
  ["How information may be shared", "Information may be shared as needed to provide services, coordinate care, process payments or insurance, meet legal obligations, protect health and safety, or work with trusted service providers supporting hosting, scheduling, communications, billing, analytics, and related operations. Service providers may use information only to perform services for us and subject to appropriate restrictions. We do not sell personal information."],
  ["SMS privacy", "Your mobile number and consent to receive texts will not be shared with any third party or affiliates for their own marketing purposes. We do not purchase, sell, rent, or use third-party SMS opt-in lists. Our SMS provider and other vendors may process your number and message information only as service providers to deliver and manage the service-related messages you requested. Reply STOP or UNSUBSCRIBE to opt out, HELP for help, or contact us by phone, email, or mail."],
  ["Protecting your information", "We use reasonable administrative, technical, and physical safeguards designed to protect information entrusted to us. No online system can be guaranteed completely secure, so please avoid sending urgent or highly sensitive medical information through ordinary email, web forms, or SMS."],
  ["Your choices and privacy questions", "You may ask us to update your contact information, manage communication preferences, answer questions about this policy, or explain how to exercise rights available to you under applicable law. We may need to verify your identity before completing a request. You may opt out of SMS at any time without affecting your access to healthcare services."],
];

export default function PrivacyPage() {
  return <div className="bg-white">
    <section className="relative overflow-hidden bg-brand-ink py-20 text-white sm:py-28"><div className="hero-grid absolute inset-0 opacity-25" /><div className="relative mx-auto max-w-3xl px-4 text-center sm:px-6"><LockKeyhole className="mx-auto h-9 w-9 text-brand-red" /><p className="mt-5 text-sm font-bold uppercase tracking-[.2em] text-brand-red">Privacy policy</p><h1 className="mt-4 text-4xl font-bold sm:text-6xl">Your information deserves care.</h1><p className="mt-6 text-lg leading-relaxed text-white/70">Effective date: September 8, 2026</p></div></section>
    <main className="mx-auto max-w-4xl px-4 py-16 sm:px-6 sm:py-24"><p className="text-lg leading-relaxed text-slate-600">Genfinity O&amp;P LLC is committed to protecting the privacy, confidentiality, and security of the information entrusted to us. This policy applies to information collected through genfinityoandp.com, our forms, and our related communications, including SMS.</p>
      <div className="mt-12 space-y-10">{sections.map(([title, body]) => <section key={title} className="border-b border-brand-ink/10 pb-10"><h2 className="text-2xl font-bold text-brand-ink">{title}</h2><p className="mt-4 leading-relaxed text-slate-600">{body}</p></section>)}</div>
      <section className="mt-12 rounded-3xl bg-brand-ink p-8 text-white sm:p-10"><h2 className="text-2xl font-bold">Questions about privacy?</h2><p className="mt-3 text-white/70">Contact Genfinity O&amp;P at <a className="hover:text-white" href="mailto:support@genfinityoandp.com">support@genfinityoandp.com</a> or at the address below. This policy may be updated from time to time; updates will be posted on this page.</p><p className="mt-5 text-white/80">GENFINITY O&amp;P LLC<br />18401 Burbank Blvd, Suite 215<br />Tarzana, CA 91356</p><a href="tel:8885526188" className="mt-6 inline-flex items-center gap-2 font-bold text-brand-red"><Phone className="h-5 w-5" /> (888) 552-6188</a></section>
      <p className="mt-8 text-sm text-slate-500">See also: <Link className="font-semibold text-brand-red" href="/terms">Terms &amp; Conditions</Link></p>
    </main>
  </div>;
}
