'use client';

import Link from 'next/link';
import { motion } from 'motion/react';
import { ArrowRight, CalendarCheck, CheckCircle2, HeartPulse, Phone, ScanLine, ShieldCheck, Sparkles } from 'lucide-react';
import { SkeletonImage } from '@/components/SkeletonImage';
import heroImage from '@/assets/images/genfinity-hero-mobility.png';

const carePaths = [
  { title: 'Custom orthotics', text: 'Support and alignment for the moments that make up your everyday life.', href: '/services/orthotics' },
  { title: 'Prosthetic care', text: 'A collaborative path to comfort, capability, and confidence in motion.', href: '/services/prosthetics' },
  { title: 'Custom insoles', text: 'Personalized foot support for pain relief, balance, and better steps.', href: '/services/custom-insoles' },
];

export default function Home() {
  return <div className="overflow-hidden bg-white">
    <section className="relative isolate bg-white pb-16 pt-10 sm:pb-24 lg:pb-32 lg:pt-20">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_10%_20%,rgba(18,90,88,.13),transparent_27%),radial-gradient(circle_at_88%_88%,rgba(175,32,31,.1),transparent_24%)]" />
      <div className="hero-grid absolute inset-0 -z-10 opacity-70" />
      <div className="absolute left-[6%] top-[12%] h-2 w-2 rounded-full bg-brand-red shadow-[0_0_0_8px_rgba(175,32,31,.10)]" />
      <div className="absolute bottom-[15%] left-[48%] h-3 w-3 rounded-full border-2 border-brand-blue/50" />
      <div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:gap-16 lg:px-8">
        <motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.55}} className="max-w-xl">
          <div className="inline-flex items-center gap-2 rounded-full border border-brand-blue/15 bg-white px-3 py-1.5 text-sm font-semibold text-brand-blue shadow-sm"><HeartPulse className="h-4 w-4 text-brand-red"/> Orthotics &amp; prosthetics care in Tarzana</div>
          <h1 className="mt-6 text-4xl font-bold leading-[1.05] text-slate-950 sm:text-5xl lg:text-6xl">Your life is still yours. <span className="text-brand-blue">Let&apos;s help you move into it.</span></h1>
          <p className="mt-6 max-w-lg text-lg leading-relaxed text-slate-600">Pain, instability, or an amputation can change the way each day feels. At Genfinity O&amp;P, you&apos;ll find attentive clinical care and a solution shaped around what matters to you.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="tel:8885526188" className="inline-flex items-center justify-center gap-2 rounded-full bg-brand-red px-7 py-3.5 font-bold text-white shadow-lg shadow-brand-red/20 transition hover:bg-brand-red-dark hover:-translate-y-0.5"><Phone className="w-5 h-5"/> Call for care</a><Link href="/request-consultation" className="inline-flex items-center justify-center gap-2 rounded-full border border-brand-blue/20 bg-white px-7 py-3.5 font-bold text-brand-blue transition hover:border-brand-blue hover:bg-brand-blue-light">Request a consultation <ArrowRight className="w-4 h-4"/></Link></div>
          <div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm font-medium text-slate-600"><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-brand-red"/> Personal clinical evaluation</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-brand-red"/> Ongoing adjustments &amp; support</span></div>
        </motion.div>
        <motion.div initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} transition={{duration:.7,delay:.1}} className="relative mx-auto w-full max-w-[620px]">
          <div className="absolute -inset-4 -z-10 rounded-[2.5rem] border border-brand-blue/15 bg-white/50" />
          <div className="relative aspect-[4/4.4] overflow-hidden rounded-[2rem] border border-white/70 bg-brand-blue shadow-2xl shadow-brand-blue/20"><SkeletonImage src={heroImage} alt="A patient with a prosthetic leg walking confidently with a clinician" fill priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-brand-blue/35 via-transparent to-transparent"/><div className="absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-brand-blue/20 to-transparent"/></div>
          <div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-white/30 bg-white/90 p-4 shadow-lg backdrop-blur sm:bottom-7 sm:left-7 sm:right-auto sm:max-w-[265px]"><p className="text-xs font-bold uppercase tracking-[.16em] text-brand-red">Care with purpose</p><p className="mt-1 font-heading text-lg font-bold leading-snug text-slate-900">Built around your goals, not a generic device.</p></div>
          <div className="absolute -right-3 top-7 hidden rounded-2xl border border-brand-blue/10 bg-white p-4 shadow-xl lg:block"><CalendarCheck className="w-6 text-brand-red"/><p className="mt-2 text-xs font-bold uppercase tracking-wider text-brand-blue">A clear next step</p></div>
        </motion.div>
      </div>
    </section>

    <section className="relative border-y border-brand-blue/10 bg-white py-7 sm:py-9"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid divide-y divide-brand-blue/10 md:grid-cols-3 md:divide-x md:divide-y-0">{[['Listen first','Your goals, concerns, lifestyle, and comfort direct the care plan.'],['Make it personal','Every device is measured, selected, and adjusted for the person using it.'],['Stay with you','We provide follow-up care as your body, device, and needs evolve.']].map(([title,text],index)=><div key={title} className="flex gap-4 py-6 md:px-7 md:first:pl-0 md:last:pr-0"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-brand-blue text-sm font-bold text-white">0{index+1}</span><div><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm leading-relaxed text-slate-600">{text}</p></div></div>)}</div></div></section>

    <section className="relative bg-white py-20 sm:py-28"><div className="hero-grid absolute inset-0 opacity-35"/><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.19em] text-brand-red">Find your path forward</p><h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl">Care that meets the challenge—and sees the person.</h2><p className="mt-5 text-lg leading-relaxed text-slate-600">Whether you&apos;re seeking relief, recovery, or a return to the activities you love, we help make the next step feel possible.</p></div><Link href="/services" className="inline-flex items-center gap-2 font-bold text-brand-blue">View all services <ArrowRight className="w-4 h-4"/></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{carePaths.map((path,index)=><motion.article initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.08}} key={path.title} className="group relative overflow-hidden rounded-3xl border border-brand-blue/10 bg-white p-7 shadow-sm transition hover:-translate-y-2 hover:border-brand-blue/30 hover:shadow-2xl hover:shadow-brand-blue/10"><span className="absolute -right-4 -top-8 font-heading text-9xl font-bold text-brand-blue/[.045]">0{index+1}</span><div className="relative grid h-12 w-12 place-items-center rounded-2xl bg-brand-blue text-white shadow-lg shadow-brand-blue/20">{index === 0 ? <ScanLine className="w-6"/> : index === 1 ? <Sparkles className="w-6"/> : <HeartPulse className="w-6"/>}</div><h3 className="relative mt-7 text-2xl font-bold text-slate-900">{path.title}</h3><p className="relative mt-3 leading-relaxed text-slate-600">{path.text}</p><Link href={path.href} className="relative mt-7 inline-flex items-center gap-2 font-bold text-brand-blue group-hover:text-brand-red">Explore care <ArrowRight className="w-4 h-4"/></Link></motion.article>)}</div></div></section>

    <section className="relative overflow-hidden bg-slate-950 py-20 text-white sm:py-28"><div className="hero-grid absolute inset-0 opacity-30 [mask-image:radial-gradient(circle_at_70%_50%,black,transparent_62%)]"/><div className="absolute -right-20 top-1/2 h-80 w-80 -translate-y-1/2 rounded-full border border-brand-blue/50"/><div className="absolute -right-5 top-1/2 h-52 w-52 -translate-y-1/2 rounded-full border border-brand-red/40"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-[1fr_.9fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[.19em] text-red-300">A better care experience</p><h2 className="mt-4 max-w-xl text-3xl font-bold leading-tight sm:text-5xl">Less uncertainty. More clarity. A team in your corner.</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-300">From the first question through fitting and adjustment, Genfinity O&amp;P gives you a clear plan and the time to understand it. We&apos;re here to help you feel capable again.</p><Link href="/what-to-expect" className="mt-8 inline-flex items-center gap-2 rounded-full border border-white/30 px-6 py-3 font-bold text-white transition hover:bg-white hover:text-brand-blue">See what to expect <ArrowRight className="w-4 h-4"/></Link></div><div className="relative grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[.07] p-7 backdrop-blur-sm"><ShieldCheck className="w-8 text-red-300"/><h3 className="mt-6 text-xl font-bold">Comfort is clinical</h3><p className="mt-3 leading-relaxed text-slate-300">Fit, function, and your feedback inform every adjustment.</p></div><div className="rounded-3xl border border-white/10 bg-white/[.07] p-7 backdrop-blur-sm sm:translate-y-8"><HeartPulse className="w-8 text-red-300"/><h3 className="mt-6 text-xl font-bold">Your goals lead</h3><p className="mt-3 leading-relaxed text-slate-300">Walk the dog. Work the shift. Feel steady. It all counts.</p></div></div></div></section>

    <section className="relative overflow-hidden bg-brand-blue py-20 text-center text-white"><div className="hero-grid absolute inset-0 opacity-20"/><div className="absolute left-1/2 top-0 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/20"/><div className="relative mx-auto max-w-3xl px-4 sm:px-6"><p className="text-sm font-bold uppercase tracking-[.19em] text-red-200">Start with a conversation</p><h2 className="mt-4 text-3xl font-bold sm:text-5xl">You don&apos;t have to figure it out alone.</h2><p className="mt-5 text-lg leading-relaxed text-blue-100">Tell us what&apos;s getting in the way. We&apos;ll help you understand the next meaningful step.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="tel:8885526188" className="inline-flex items-center justify-center gap-2 rounded-full bg-brand-red px-7 py-3.5 font-bold text-white shadow-xl shadow-slate-950/20 transition hover:bg-brand-red-dark hover:-translate-y-0.5"><Phone className="w-5 h-5"/> (888) 552-6188</a><Link href="/request-consultation" className="inline-flex items-center justify-center rounded-full border border-white/40 px-7 py-3.5 font-bold transition hover:bg-white hover:text-brand-blue">Request a consultation</Link></div></div></section>
  </div>;
}
