import Link from 'next/link';
import { FileText, Phone } from 'lucide-react';

const terms = [
  ['Acceptance of terms', 'By accessing this website, scheduling appointments, submitting forms, or opting into communications, you agree to these Terms & Conditions and the Privacy Policy.'],
  ['Healthcare services disclaimer', 'Website, form, and communication content is provided for general informational purposes only. It is not medical advice, diagnosis, or treatment. A provider-patient relationship is established only through appropriate clinical evaluation and acceptance as a patient.'],
  ['Appointment requests and communications', 'When you submit information through the website or another approved channel, you authorize Genfinity O&P to contact you about scheduling, reminders, follow-up care, insurance, billing, customer support, and service-related updates.'],
  ['SMS terms of service', 'SMS consent is voluntary and is not a condition of receiving healthcare services. Messages may include appointment reminders and confirmations, follow-up and treatment-related notices, insurance and billing updates, customer care, and service-related information. Message frequency varies and message/data rates may apply.'],
  ['SMS controls', 'Reply STOP to any text message to opt out. Reply HELP for assistance, or contact our office at (888) 552-6188. SMS consent is not shared with third parties or affiliates for marketing purposes.'],
  ['Your responsibilities', 'You agree to provide accurate information, keep your contact details current, use the website lawfully, and not attempt unauthorized access to systems or data.'],
  ['Intellectual property and third parties', 'Genfinity O&P website content, branding, graphics, forms, documents, and materials are protected. We may use third-party providers for website hosting, scheduling, communications, payments, analytics, and related operations.'],
  ['Changes and governing law', 'Terms may be updated by posting a revised version on this site. These Terms are governed by the laws of the State of California.'],
];

export default function TermsPage() { return <div className="bg-white"><section className="relative overflow-hidden bg-brand-ink py-20 text-white sm:py-28"><div className="hero-grid absolute inset-0 opacity-25"/><div className="relative mx-auto max-w-3xl px-4 text-center sm:px-6"><FileText className="mx-auto h-9 w-9 text-brand-red"/><p className="mt-5 text-sm font-bold uppercase tracking-[.2em] text-brand-red">Terms &amp; conditions</p><h1 className="mt-4 text-4xl font-bold sm:text-6xl">Clear terms for clear care.</h1><p className="mt-6 text-lg text-white/70">Effective date: January 1, 2026</p></div></section><main className="mx-auto max-w-4xl px-4 py-16 sm:px-6 sm:py-24"><p className="text-lg leading-relaxed text-slate-600">These Terms &amp; Conditions govern use of Genfinity O&amp;P&apos;s website, services, communications, and SMS messaging program.</p><div className="mt-12 space-y-10">{terms.map(([title,body])=><section key={title} className="border-b border-brand-ink/10 pb-10"><h2 className="text-2xl font-bold text-brand-ink">{title}</h2><p className="mt-4 leading-relaxed text-slate-600">{body}</p></section>)}</div><section className="mt-12 rounded-3xl border border-brand-ink/10 p-8 sm:p-10"><h2 className="text-2xl font-bold text-brand-ink">Contact information</h2><p className="mt-4 leading-relaxed text-slate-600">GENFINITY O&amp;P LLC<br/>18401 Burbank Blvd, Suite 215<br/>Tarzana, California 91356</p><a href="tel:8885526188" className="mt-5 inline-flex items-center gap-2 font-bold text-brand-red"><Phone className="w-5 h-5"/> (888) 552-6188</a></section><p className="mt-8 text-sm text-slate-500">See also: <Link className="font-semibold text-brand-red" href="/privacy">Privacy &amp; Policies</Link></p></main></div>; }
