import Link from 'next/link';
import { ChevronRight, CircleHelp, Phone } from 'lucide-react';

const faqs = [
  ['I am not sure whether I need an orthotist or prosthetist. Can I still call?', 'Yes. You do not need to diagnose yourself or know the name of a device. Tell us what is painful, unstable, missing, or difficult. We will help determine the appropriate next step.'],
  ['Do I need a prescription?', 'Many custom orthotic and prosthetic devices—and many insurance plans—require a prescription or medical documentation. Call before your visit so we can explain what may be needed for your specific situation.'],
  ['What should I bring to my first appointment?', 'Bring your photo ID, insurance card, prescription or referral if available, a medication or diagnosis list if relevant, and any brace, prosthesis, insole, mobility device, or footwear you currently use.'],
  ['How long will the process take?', 'The timeline depends on the device, clinical complexity, fabrication, availability of components, documentation, and insurance authorization. We will give you the clearest estimate possible after evaluation and keep you informed if something changes.'],
  ['Will my device feel perfect immediately?', 'Some devices feel comfortable quickly; others require a break-in period, training, or follow-up adjustment. Pain, skin problems, instability, or a sudden change should be reported rather than tolerated.'],
  ['Do you help with insurance?', 'We can review available benefits and authorization requirements and coordinate documentation when appropriate. Verification is not a guarantee of payment because the insurer makes the final coverage decision.'],
  ['What is the difference between a custom-fabricated and custom-fit orthosis?', 'A custom-fabricated orthosis is made specifically from your measurements, cast, or scan. A custom-fit orthosis begins as a prefabricated device, then is selected and adjusted to your body and needs.'],
  ['What do AFO, KAFO, and TLSO mean?', 'Orthoses are often named for the body parts or joints they support. AFO means ankle-foot orthosis, KAFO means knee-ankle-foot orthosis, and TLSO means thoracic-lumbar-sacral orthosis. We will always explain these terms in plain English.'],
  ['What do below-knee and above-knee prosthesis mean?', 'A below-knee prosthesis may also be called transtibial. An above-knee prosthesis may be called transfemoral. The correct plan depends on the amputation level, limb condition, strength, goals, and many other individual factors.'],
  ['Can you adjust a device I already use?', 'Often, an evaluation can identify whether adjustment, repair, replacement, or a different solution is appropriate. Bring the device with you and describe exactly what is not working.'],
  ['What should I do in a medical emergency?', 'Call 911 or seek emergency medical care. This website, email, and routine clinic communications are not monitored for emergencies.'],
];

export default function FAQs(){return <div className="bg-white"><section className="bg-brand-ink py-20 text-center text-white sm:py-28"><CircleHelp className="mx-auto h-10 w-10 text-brand-red"/><p className="mt-5 text-sm font-bold uppercase tracking-[.2em] text-brand-red">Straight answers</p><h1 className="mt-4 text-4xl font-bold sm:text-6xl">Questions are part of good care.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-white/70">You are not expected to arrive knowing the terminology. We explain what matters and make the next step easier to understand.</p></section><main className="mx-auto max-w-4xl px-4 py-16 sm:px-6 sm:py-24"><div className="space-y-4">{faqs.map(([question,answer],i)=><article key={question} className="rounded-2xl border border-brand-ink/10 p-6 sm:p-7"><div className="flex gap-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-brand-red text-xs font-bold text-white">{i+1}</span><div><h2 className="text-xl font-bold text-brand-ink">{question}</h2><p className="mt-3 leading-relaxed text-slate-600">{answer}</p></div></div></article>)}</div><div className="mt-12 flex flex-col items-start justify-between gap-5 rounded-3xl bg-brand-ink p-8 text-white sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold">Your question is not “too small.”</h2><p className="mt-1 text-white/70">Call us and tell us what you are worried about.</p></div><a href="tel:8885526188" className="inline-flex items-center gap-2 rounded-full bg-brand-red px-5 py-3 font-bold"><Phone className="w-4 h-4"/> Call now</a></div><Link href="/patient-resources" className="mt-8 inline-flex items-center gap-2 font-bold text-brand-red">More patient resources <ChevronRight className="w-4 h-4"/></Link></main></div>}
